wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 96
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.6447587793108374
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.19718354619480716
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.3826780513117896
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.6551177060180953
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.9283796007256244
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.24125662866529507
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.3298586368357609
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.4485212871880604
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.6335331154699272
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.4163750723902354
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.3070032322520124
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.1874835273112928
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.23710882251917553
model.train_sys.steps.0.epochs:
  value: 39
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.3464555093176338
model.train_sys.steps.0.model.drop_rate:
  value: 0.016873028320795735
model.train_sys.steps.0.model.model_name:
  value: levit_conv_192
model.train_sys.steps.0.optimizer.lr:
  value: 0.007005058320101262
