wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 102
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.2067765359411865
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.05285539744721712
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.1328703546562241
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.020114800070307193
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.5632180260678429
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.0005112117764899393
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.660801227168141
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.27084679687737334
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.04578853146793693
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.7172223475517283
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.38059885685301464
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.3870300392928336
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.07846880238720355
model.train_sys.steps.0.epochs:
  value: 30
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.018854362834246408
model.train_sys.steps.0.model.drop_rate:
  value: 0.2976583063660075
model.train_sys.steps.0.model.model_name:
  value: beit_base_patch16_224
model.train_sys.steps.0.optimizer.lr:
  value: 0.007852505920121888
