wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 80
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.7013022914978319
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.3246966382838886
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.8604319128345168
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.6645301316641845
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.32590794393144273
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.5319260677831017
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.3838125940621323
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.003964677616685619
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.659003358611711
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.9824593544777483
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.027939907031961583
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.28893083121524266
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.6456433013354208
model.train_sys.steps.0.epochs:
  value: 24
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.4668038489734681
model.train_sys.steps.0.model.drop_rate:
  value: 0.292962942879206
model.train_sys.steps.0.model.model_name:
  value: efficientnetv2_s
model.train_sys.steps.0.optimizer.lr:
  value: 0.0003867713587695503
