wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 93
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.7675520164267353
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.6053559026531004
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.22731288696304497
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.43010679306912913
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.3641517673447974
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.012403605670516347
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.7346163381566283
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.18975760976242084
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.27958816320532154
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.07072939617433227
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.21974051770446756
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.35546279625338717
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.3443558447784687
model.train_sys.steps.0.epochs:
  value: 42
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.3508677988707654
model.train_sys.steps.0.model.drop_rate:
  value: 0.017815311306654036
model.train_sys.steps.0.model.model_name:
  value: convnext_tiny
model.train_sys.steps.0.optimizer.lr:
  value: 0.001509225789461582
