wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 96
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.10647910039874942
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.468415665510393
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.24421958210613093
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.8982070570715455
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.11299090466351223
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.1711070661245233
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.6130068470589359
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.5181849503196303
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.7663673680865126
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.6679029319201417
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.9224610095221584
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.9025840454489424
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.3798213307255385
model.train_sys.steps.0.epochs:
  value: 54
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.4887279897093349
model.train_sys.steps.0.model.drop_rate:
  value: 0.4236961320819513
model.train_sys.steps.0.model.model_name:
  value: resnet34
model.train_sys.steps.0.optimizer.lr:
  value: 0.0033053977037355103
