wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 43
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.940824616240876
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.34706837672564883
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.7124912079366537
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.2940912862285545
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.21214646024005632
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.6934454954741247
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.45997974932636254
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.4168562971945965
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.6823507122323587
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.21422294063174907
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.9491775618283934
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.11348266060873125
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.2502318314734757
model.train_sys.steps.0.epochs:
  value: 61
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.19309950738212467
model.train_sys.steps.0.model.drop_rate:
  value: 0.2264701600395305
model.train_sys.steps.0.model.model_name:
  value: efficientnet_b4
model.train_sys.steps.0.optimizer.lr:
  value: 0.00011913677957480448
