wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 32
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.6754872996760238
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.8933851076456472
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.07854928332613376
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.728559690070687
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.2619987036857666
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.08777090551811861
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.90646440521753
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.8570453382586806
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.34894204656075767
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.2972307175526503
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.31903082600682875
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.9258496515610402
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.4132132238679487
model.train_sys.steps.0.epochs:
  value: 67
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.07710369767065955
model.train_sys.steps.0.model.drop_rate:
  value: 0.11595706805724164
model.train_sys.steps.0.model.model_name:
  value: vgg11
model.train_sys.steps.0.optimizer.lr:
  value: 0.001195769747165403
