wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 55
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.968203981797506
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.955130727528716
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.941751016042614
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.16011998655095228
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.8166444025016164
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.7749051957046343
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.09735039731404416
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.13260139048996622
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.2777592970915559
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.1034573702240581
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.6440434223737477
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.5876871748835792
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.025971802811394214
model.train_sys.steps.0.epochs:
  value: 68
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.3766717214255133
model.train_sys.steps.0.model.drop_rate:
  value: 0.22578915609492933
model.train_sys.steps.0.model.model_name:
  value: efficientnet_b4
model.train_sys.steps.0.optimizer.lr:
  value: 0.0038713984607216608
