wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 88
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.33790896411510696
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.17175373014870876
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.5832064964674231
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.9057886322902412
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.48334572145543553
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.9134808013309752
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.8720288447744026
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.7113738682599692
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.2645972577160469
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.6178780035884529
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.02695442943644122
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.5535378635933469
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.14690552839735926
model.train_sys.steps.0.epochs:
  value: 61
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.019055490646760764
model.train_sys.steps.0.model.drop_rate:
  value: 0.4605612970518879
model.train_sys.steps.0.model.model_name:
  value: resnet34
model.train_sys.steps.0.optimizer.lr:
  value: 0.008219245848597912
