wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 61
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.15090832630364148
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.569727147993132
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.5162985550346774
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.4616037978253113
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.6714924844039758
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.8941514452667912
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.2777945354433652
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.28074632779828124
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.01956669102390451
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.3060678420271846
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.8774474552045718
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.39518783244609945
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.398490892220869
model.train_sys.steps.0.epochs:
  value: 70
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.27282315993247663
model.train_sys.steps.0.model.drop_rate:
  value: 0.19578186759925592
model.train_sys.steps.0.model.model_name:
  value: resnet50
model.train_sys.steps.0.optimizer.lr:
  value: 0.01052695611441138
