wandb_version: 1

model.train_sys.steps.0.batch_size:
  value: 21
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.0.p:
  value: 0.6788371971754447
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.1.p:
  value: 0.13700828382794672
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.0.p:
  value: 0.9786306784253396
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.1.p:
  value: 0.2411953636503136
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.2.p:
  value: 0.8448377931669546
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.3.p:
  value: 0.20302299343509067
model.train_sys.steps.0.dataset_args.aug_1d.x_transforms.2.compose.transforms.4.p:
  value: 0.2772687103810497
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.0.p:
  value: 0.8479195519659048
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.1.p:
  value: 0.32381071230589475
model.train_sys.steps.0.dataset_args.aug_1d.xy_transforms.2.p:
  value: 0.4823290581242121
model.train_sys.steps.0.dataset_args.aug_2d.x_transforms.0.p:
  value: 0.0703524594560696
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.0.p:
  value: 0.9183651919172886
model.train_sys.steps.0.dataset_args.aug_2d.xy_transforms.1.p:
  value: 0.6036522957128384
model.train_sys.steps.0.epochs:
  value: 63
model.train_sys.steps.0.model.drop_path_rate:
  value: 0.3217354750858475
model.train_sys.steps.0.model.drop_rate:
  value: 0.22864978340410472
model.train_sys.steps.0.model.model_name:
  value: resnet34
model.train_sys.steps.0.optimizer.lr:
  value: 0.004941938781116775
