defaults:
  - base_cv
  - hydra/logging
  - model: b0_aug # Add models or ensembles
  - wandb: train

###############
#             #
#    PATHS    #
#             #
###############
processed_path: data/processed/
raw_path: data/raw/
cache_path: data/cache
years: ["2023", "2024"]
#data_path: data/raw/train_data/dummy.npy
data_path: data/raw/train_audio/
metadata_path: data/raw/train_metadata.csv

scorer:
  _target_: src.scoring.rocauc.ROCAUC # Add scorer
  name: rocauc
  grade_threshold: 0
  only_primary: true
splitter:
  _target_: src.setup.splitter.Splitter
  splitter:
    _target_: functools.partial
    _args_:
      - _target_: hydra.utils.get_class
        path: sklearn.model_selection.StratifiedKFold
  n_splits: 5 # Set to 0 if you want train full.
  shuffle: true
  random_state: 42
  years: ["2023","2024"]
allow_multiple_instances: true
