defaults:
  - base_cv
  - hydra/logging
  - model: playful-monkey-752  # Add models or ensembles
  - wandb: submit

###############
#             #
#    PATHS    #
#             #
###############
processed_path: data/processed/
raw_path: data/raw/
cache_path: data/cache
years: ["2024"]

data_path: data/raw/2024/train_audio/
metadata_path: data/raw/2024/train_metadata.csv

scorer:
  _target_: src.scoring.rocauc_years.ROCAUC # Add scorer
  name: rocauc
  grade_threshold: 0
  only_primary: true

splitter:
  _target_: src.setup.splitter.Splitter
  splitter:
    _target_: functools.partial
    _args_:
      - _target_: hydra.utils.get_class
        path: sklearn.model_selection.StratifiedKFold
  n_splits: 5 # Set to 0 if you want train full.
  shuffle: true
  random_state: 42
  years: ["2024"]
allow_multiple_instances: true
#corr_weight: 0.5
