defaults:
  - base_train
  - hydra/logging
  - model: alternate-ensemble[pry46jiv,uubbpt64]
  - wandb: train

###############
#             #
#    PATHS    #
#             #
###############
processed_path: data/processed/
raw_path: data/raw/
years: ["2024"]
cache_path: data/cache
#data_path: data/raw/train_data/dummy.npy
data_path: data/raw/2024/train_audio/
metadata_path: data/raw/2024/train_metadata.csv

# Do this if you want train full.
test_size: 0.2

scorer:
  _target_: src.scoring.rocauc_years.ROCAUC # Add scorer
  name: rocauc
  grade_threshold: 0
  only_primary: true
splitter:
  _target_: src.setup.splitter.Splitter
  splitter:
    _target_: functools.partial
    _args_:
      - _target_: hydra.utils.get_class
        path: sklearn.model_selection.StratifiedKFold
  n_splits: 5 # Set to 0 if you want train full.
  shuffle: true
  random_state: 42
  years: ["2024"]
allow_multiple_instances: true
