defaults:
  - base_train
  - hydra/logging
  - model: convnext-post-freefield # Add models or ensembles
  - wandb: train

###############
#             #
#    PATHS    #
#             #
###############
processed_path: data/processed/
raw_path: data/raw/
years: ["freefield"]
cache_path: data/cache

data_path: data/raw/2024/train_audio/
metadata_path: data/raw/2024/train_metadata.csv

# Do this if you want train full.
test_size: 0.2

# Species cap
#max_recordings_per_species: 500

#scorer:
#  _target_: src.scoring.rocauc_years.ROCAUC # Add scorer
#  name: rocauc
#  grade_threshold: 0
#  only_primary: true

scorer:
  _target_: src.scoring.accuracy.Accuracy # Add scorer
  name: acc
splitter:
  _target_: src.setup.splitter.Splitter
  splitter:
    _target_: functools.partial
    _args_:
      - _target_: hydra.utils.get_class
        path: sklearn.model_selection.StratifiedKFold
  n_splits: 5 # Set to 0 if you want train full.
  shuffle: true
  random_state: 42
  years: ["freefield"]
allow_multiple_instances: true
