_target_: epochalyst.pipeline.model.model.ModelPipeline
_convert_: partial
x_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Preprocessing pipeline
  steps:
  - _target_: src.modules.transformation.x.nan_to_zero.NanToZero
    years:
    - '2023'
    - 'kenya'
y_sys: null
train_sys:
  _target_: src.modules.training.verbose_training_pipeline.VerboseTrainingPipeline
  steps:
  - _target_: src.modules.training.double_trainer.DoubleTrainer
    year: 'union_2023_kenya'
    dataset_args:
      sampler:
        _target_: src.modules.training.datasets.sampler.crop_or_pad.CropOrPad
        length: 160000
      to_2d:
        _target_: src.modules.training.datasets.to_2d.spec.Spec
        spec:
          _target_: functools.partial
          _args_:
          - _target_: hydra.utils.get_class
            path: torchaudio.transforms.MelSpectrogram
        output_shape:
        - 224
        - 224
        scale:
          _target_: src.modules.training.datasets.to_2d.spec_normalize.SpecNormalize
      labeler:
        _target_: src.modules.training.datasets.labeler.psd_labeler.PSDLabeler
      filter_:
        _target_: src.modules.training.datasets.filter.grade_threshold.GradeThreshold
        threshold: 0

    dataloader_args:
      num_workers: 8
      prefetch_factor: 2
      persistent_workers: false
    n_folds: 5
    epochs: 50
    patience: 15
    batch_size: 64
    model:
      _target_: src.modules.training.models.double_model.DoubleModel
      model:
        _target_: src.modules.training.models.timm.Timm
        in_channels: 1
        out_channels: 432
        model_name: convnext_tiny
        activation: sigmoid
    scheduler:
      _target_: functools.partial
      _args_:
      - _target_: hydra.utils.get_class
        path: timm.scheduler.cosine_lr.CosineLRScheduler
      warmup_t: 3
      warmup_lr_init: 1.0e-05
      t_initial: 50
      cycle_limit: 1
    criterion:
      _target_: src.modules.training.losses.double_loss.DoubleLoss
      target_loss: torch.nn.BCELoss
      call_loss: torch.nn.BCELoss
    optimizer:
      _target_: functools.partial
      _args_:
      - _target_: hydra.utils.get_class
        path: torch.optim.AdamW
      lr: 0.0005
  - _target_: src.modules.training.postprocessing.smooth_file.SmoothFile
    smooth_factor: 0.75
  - _target_: src.modules.training.postprocessing.keep_2024_species.Keep2024Species
pred_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Postprocessing pipeline
label_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
