_target_: epochalyst.pipeline.model.model.ModelPipeline
_convert_: partial
x_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Preprocessing pipeline
  steps:
  - _target_: src.modules.transformation.x.nan_to_zero.NanToZero
    years:
    - '2024'
y_sys: null
train_sys:
  _target_: src.modules.training.verbose_training_pipeline.VerboseTrainingPipeline
  steps:
  - _target_: src.modules.training.main_trainer.MainTrainer
    year: '2024'
    dataset_args:
      sampler:
        _target_: src.modules.training.datasets.sampler.crop_or_pad.CropOrPad
        length: 160000
      to_2d:
        _target_: src.modules.training.datasets.to_2d.spec.Spec
        spec:
          _target_: functools.partial
          _args_:
          - _target_: hydra.utils.get_class
            path: torchaudio.transforms.MelSpectrogram
        output_shape:
        - 128
        - 256
        scale:
          _target_: src.modules.training.datasets.to_2d.spec_normalize.SpecNormalize
      labeler:
        _target_: src.modules.training.datasets.labeler.psd_labeler.PSDLabeler
      filter_:
        _target_: src.modules.training.datasets.filter.grade_threshold.GradeThreshold
        threshold: 0
      process_delayed:
        - _target_: src.modules.transformation.x.rescale.Rescale
      aug_1d:
        _target_: epochalyst.pipeline.model.training.augmentation.utils.CustomSequential
        x_transforms:
      #   - _target_: epochalyst.pipeline.model.training.augmentation.time_series_augmentations.RandomPhaseShift
      #     p: 0.5
      #     shift_limit: 0.5
        - _target_: epochalyst.pipeline.model.training.augmentation.time_series_augmentations.RandomAmplitudeShift
          p: 0.5
        - _target_: src.modules.training.augmentations.audiomentations_compose.AudiomentationsCompose
          compose:
            _target_: audiomentations.Compose
            transforms:
            - _target_: audiomentations.PolarityInversion
              p: 0.5

            - _target_: audiomentations.AddBackgroundNoise
              p: 0.5
              sounds_path: /home/tolga/Documents/q4-bird-clef/data/raw/esc50/audio/
              min_snr_db: -3.0
              max_snr_db: 3.0
              noise_transform:
                _target_: audiomentations.PolarityInversion
                p: 0.5

            - _target_: audiomentations.AddColorNoise
              p: 0.5
              min_snr_db: -3.0
              max_snr_db: 3.0
            - _target_: audiomentations.PitchShift
              p: 0.5

            - _target_: audiomentations.Shift
              p: 0.5

        xy_transforms:
        - _target_: src.modules.training.augmentations.time_series_augmentations.EnergyCutmix
          p: 0.5
        - _target_: epochalyst.pipeline.model.training.augmentation.time_series_augmentations.MixUp1D
          p: 0.5
      aug_2d:
        _target_: epochalyst.pipeline.model.training.augmentation.utils.CustomSequential
        xy_transforms:
        - _target_: epochalyst.pipeline.model.training.augmentation.image_augmentations.MixUp
          p: 0.5
    dataloader_args:
      num_workers: 16
      prefetch_factor: 1
      persistent_workers: false
    n_folds: 5
    epochs: 50
    patience: 15
    batch_size: 64
    model:
      _target_: src.modules.training.models.fdy_sed.CRNN
      n_input_ch: 1
      n_class: 182
      n_RNN_cell: 256
      n_RNN_layer: 2
      rec_dropout: 0
      attention: class                      # time / class

      activation: cg
      conv_dropout: 0.5
      kernel: [ 3, 3, 3, 3, 3, 3, 3 ]
      pad: [ 1, 1, 1, 1, 1, 1, 1 ]
      stride: [ 1, 1, 1, 1, 1, 1, 1 ]
      n_filt: [ 32, 64, 128, 256, 256, 256, 256 ]
      pooling: [ [ 2, 2 ], [ 2, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ], [ 1, 2 ] ]

      n_basis_kernels: 4
      DY_layers: [ 0, 1, 1, 1, 1, 1, 1 ]
      temperature: 31
      pool_dim: time                       # leave time: "freq", pool time "time", pool both: "both"

    scheduler:
      # _target_: functools.partial
      # _args_:
      # - _target_: hydra.utils.get_class
      #   path: timm.scheduler.cosine_lr.CosineLRScheduler
      # warmup_t: 50
      # warmup_lr_init: 1.0e-05
      # t_initial: 200
      # cycle_limit: 1
    criterion:
      _target_: src.modules.training.losses.asymmetric_focal_loss.AsymmetricalFocalLoss
    optimizer:
      _target_: functools.partial
      _args_:
      - _target_: hydra.utils.get_class
        path: torch.optim.AdamW
      lr: 1e-3
  # - _target_: src.modules.training.postprocessing.smooth_file.SmoothFile
  #   smooth_factor: 0.75
pred_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
  title: Postprocessing pipeline
label_sys:
  _target_: src.modules.transformation.verbose_transformation_pipeline.VerboseTransformationPipeline
