defaults:
  - /model/convnext-post@steps.0
  - /model/eca@steps.1

prediction_time: 6750  # Seconds = 115 Minutes

_target_: src.modules.ensemble.timed_voting_ensemble.TimedVotingEnsemble
_convert_: partial

post_process:
  - _target_: src.modules.training.postprocessing.multiply_mean.MultiplyMean
#  - _target_: src.modules.training.postprocessing.visualize_preds.VisualizePreds
