defaults:
  - /model/convnext-post-add@steps.0
  - /model/convnext-post-add@steps.1

weights:
  - 0.5
  - 0.5

prediction_time: 25

_target_: src.modules.ensemble.timed_voting_ensemble.TimedVotingEnsemble
_convert_: partial
