defaults:
  - /model/convnext-post-add@steps.0
  - /model/convnext-post-add@steps.1

weights:  # Unused for TimedVotingEnsemble, all models are weighted equally
  - 0.5
  - 0.5

prediction_time: 6900  # Seconds = 115 Minutes

_target_: src.modules.ensemble.timed_voting_ensemble.TimedVotingEnsemble
_convert_: partial
